str1 = input("Enter a string: ")
str2 = input("Enter another string: ")
print("the string is:",str1)
print(str1[::])
print(str1[0])
print(str1[0:3])
print(str1[0:3:2])
print(str1[:4])
print(str1[3:])
print(str1*2)
print(str1 + str2)
del str2