n1 = int(input(" Enter first number : "))
n2 = int(input(" Enter second number : "))

print(" Addition is",n1 + n2)
print(" Subtraction is",n1 - n2)
print(" Multiplication is",n1 * n2)
print(" Division is",n1 / n2)
print(" Modulo is",n1 % n2)
print(" Power is",n1 ** n2)
print(" Floor Division is",n1 // n2)